language: java
jdk:
  - oraclejdk7
  - openjdk7
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: mortonl/pojo-unit
      branch: master
      jdk: oraclejdk7
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: mortonl/pojo-unit
      tags: true
      jdk: oraclejdk7